name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint (Optional)
        run: echo "Add linting later if needed"

      - name: Replace env variables in task definition
        run: |
          sed -e "s|\${PORT}|${{ secrets.PORT }}|g" \
              -e "s|\${MONGO_URI}|${{ secrets.MONGODB_URI }}|g" \
              .github/ecs/ecs-task-def.json > task-def.json

      - name: Run Tests (Optional)
        run: echo "Add tests later if needed"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/product-catalog:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/product-catalog:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: Force new deployment of ECS service
        run: |
          aws ecs update-service --cluster product-catalogcluster-sample \
                                 --service product-catalog-service \
                                 --force-new-deployment
